### PR TITLE
Fix for #59 (Textbox width issue)

### LINKED ISSUE #59: Visual bug
screenshot_2018-07-03 splash community

Can you leave a space from the right of the textbox?

### PR DESCRIPTION
**Pull request by ardacebi**
Fixes the textbox width problem by adding a width section to RecipientsInput inside search.less set to 95%.

Fixes #59

### CODE REVIEW

**Comment by TurboProgramming** [comment]
@luceos I know that your priorities are currently not Flagrow, but this PR doesn't have any conflicts, it works like charm and it's easily mergeable.

Can you merge this so we'll also close #59?

**Comment by ardacebi** [comment]
## Before

42243688-d3ad6f5e-7f1a-11e8-98a2-2ccb4b579874

## After

screenshot_2018-08-22 forum photoshotclub 2

**Comment by luceos** [comment]
I personally think that using a percentage width is not the solution. Preferably this should be done using margins..

**Comment by ardacebi** [comment]
@luceos Okay, I'm trying now.

**Comment by ardacebi** [comment]
@luceos This is my best if we try fixing it with margins:

screenshot_2018-08-22 forum photoshotclub 3

```
.AddRecipientModal-form .RecipientsInput {
    overflow: hidden;
    height: auto;
    float: left;
    margin-left: -12px;
}
```

```
.AddRecipientModal-form .RecipientsInput-selected {
    margin: 2vh -12px;
}
```

**Comment by ardacebi** [comment]
If that's okay, I will change the current code on the PR to that.

**Comment by luceos** [comment]
Haven't looked into this yet but I dislike a float and negative margins on an input. Most likely the parent element needs a relative position to make the width 100% plus margins work properly.

**Comment by luceos** [comment]
this is not an issue anymore

**Pull request closed without merging**
